version: 2.1

orbs:
  android: circleci/android@1.0.0  # Updated orb version

jobs:
  build:
    executor: android/android
    steps:
      - checkout
      - restore_cache:
          keys:
            - android-orb-v1-{{ checksum "build.gradle" }}-{{ checksum "app/build.gradle" }}  # More specific cache key
            - android-orb-v1-
      - run:
          name: Chmod permissions
          command: chmod +x ./gradlew
      - run:
          name: Download Dependencies
          command: ./gradlew androidDependencies
      - save_cache:
          paths:
            - ~/.android/build-cache
            - ~/.gradle/caches
            - ~/.gradle/wrapper
          key: android-orb-v1-{{ checksum "build.gradle" }}-{{ checksum "app/build.gradle" }}
      - run:
          name: Run Build
          command: ./gradlew build
      - store_artifacts:
          path: app/build/reports
          destination: reports
      - run:
          name: Run Tests
          command: ./gradlew lint test
      - store_test_results:
          path: app/build/test-results
      - store_artifacts:
          path: app/build/outputs/apk/debug/
          destination: apk-debug